### ISSUE TITLE
Does the notebook run in a local environment?

### ISSUE THREAD

**Issue by oscarbau** [eds-book/eds-book#174]
Local environment and OS

**Comment by oscarbau** [comment]
I suggest that you describe the OS you used to run the analysis and provide some alternatives to download the data on other OS such as Windows (requests, urllib or pooch).

**Comment by acocac** [comment]
Thanks @oscarbau for the feedback on the notebook you're reviewing. Note you should report this directly in the notebook repository instead of the EDS book host repository. Bear in mind we usually create lock environments for the main OS (windows, mac, linux) to all notebooks published in EDS book. However, these files are created after the review stage.

**Comment by acocac** [comment]
Issue mirrored in the Notebook Repository.
