### ISSUE TITLE
[DOC] It's quite hard to actually find content in the book

### ISSUE THREAD

**Issue by richardclegg** [eds-book/eds-book#56]
## Feature Request

I was recommended the book during a presentation about it and was told this was the link to browse.

https://the-environmental-ds-book.netlify.app/welcome.html

When I browsed the book I first clicked on Oceans but it says "under construction" I then clicked "Forests" it said the same. I think clicked on Forest: Sensors. It also said under construction. 

As a casual reader it was difficult to find the non-blank parts of the book. To be honest, if I had had less time I would have simply assumed there was an error and the book was completely empty.

## Describe the solution you'd like

Is there some way the filled in sections could be highlighted more prominently or the generic sections (E.g. Forest, Ocean) could contains pointers to actual content. 

## Describe alternatives you've considered

Any mechanism that made the filled in sections more prominent than the non filled in ones would work. But I'm not familiar enough with the technology that turns text into the book to make a coherent suggestion.

**Comment by acocac** [comment]
@richardclegg I'm glad to hear the initiative was recommended. We really value any feedback of the book content. Note, the project is still in beta version so we expect to increase the plain content in the next months. Also, we're looking more efficient software oriented solutions to host the executable notebooks. The current version hosts all notebooks in the main repo and this will affect the size of the repository in the long term.  Also, we would like to support open-source developments in other programming language different to python. Your issue is now in the [project roadmap](https://github.com/alan-turing-institute/environmental-ds-book/projects/1) dashboard. 
Thank you! 🌍

**Comment by richardclegg** [comment]
Thanks very much. Good lock with it.
